name: Deploy Sportkamasutra Fancy

on: [push]

jobs:
 build:
   name: Build
   runs-on: ubuntu-latest
   steps:
   - name: executing remote ssh commands using password
     uses: appleboy/ssh-action@master
     with:
       host: api.timos.design
       username: root
       password: ${{ secrets.pw }}
       port: 22
       script: /root/Timos-Dev/deploy.bash
 
